Add files via upload

diff --git a/Plus b/Plus
--- a/Plus
+++ b/Plus
@@ -1,87 +1,78 @@
 #!/bin/bash
 clear
-apt-get update -y; apt-get upgrade -y; apt install curl
-clear
-if [ "${EUID}" -ne 0 ]; then
-		echo "You need to run this script as root"
-		exit 1
-fi
-if [ "$(systemd-detect-virt)" == "openvz" ]; then
-		echo "OpenVZ is not supported"
-		exit 1
-
-_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
+[[ $EUID -ne 0 ]] && {
+echo -e "\033[1;33mExcuse me, \033[1;33myou need to run as root\033[0m"
+rm -rf $HOME/Plus > /dev/null 2>&1; exit 0
+}
+_lnk=$(echo '9:q-7gs1.o1%5:f1.6q5.×9%y4:1'|sed -e 's/[^0-9.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 cd $HOME
 fun_bar () {
-comando[0]="$1"
-comando[1]="$2"
+command[0]="$1"
+command[1]="$2"
  (
-[[ -e $HOME/fim ]] && rm $HOME/fim
-${comando[0]} -y > /dev/null 2>&1
-${comando[1]} -y > /dev/null 2>&1
+[[ -e $HOME/end ]] && rm $HOME/end
+${command[0]} -y > /dev/null 2>&1
+${command[1]} -y > /dev/null 2>&1
 touch $HOME/fim
  ) > /dev/null 2>&1 &
  tput civis
-echo -ne "  \033[1;33mHOLD \033[1;37m- \033[1;33m["
+echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
 while true; do
    for((i=0; i<18; i++)); do
    echo -ne "\033[1;31m#"
    sleep 0.1s
    done
-   [[ -e $HOME/fim ]] && rm $HOME/fim && break
+   [[ -e $HOME/end ]] && rm $HOME/end && break
    echo -e "\033[1;33m]"
    sleep 1s
    tput cuu1
    tput dl1
-   echo -ne "  \033[1;33mHOLD \033[1;37m- \033[1;33m["
+   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
 done
 echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
 tput cnorm
 }
-fi
-
-red='\e[1;31m'
-green='\e[0;32m'
-NC='\e[0m'
-MYIP=$(wget -qO- icanhazip.com);
-echo -e "\033[1;31mChecking VPS\033[0m"
-sleep 2
-IZIN=$(curl https://raw.githubusercontent.com/rockneters/cmorgan/main/System/daftarIP | grep $MYIP)
-if [ $MYIP = $IZIN ]; then
-clear
-clear
-echo ""
-echo -e "${green}Permintaan Diterima...${NC}"
-echo ""
-echo "Wait.............."
-sleep 2s
+function verif_key () {
+krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
+[[ ! -e "$_Ink/list" ]] && {
+  echo -e "\n\033[1;31mINVALID KEY!\033[0m"
+  rm -rf $HOME/Plus > /dev/null 2>&1
+  sleep 2
+  clear; exit 1
+}
+}
 echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "WELCOME TO SSHPLUS MANAGER" ; tput sgr0
 echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
 echo ""
-echo -e "\033[1;31mATTENTION! \033[1;33mTHIS SCRIPT WILL!\033[0m"
+echo -e "             \033[1;31mATTENTION! \033[1;33mTHIS SCRIPT WILL!\033[0m"
 echo ""
 echo -e "\033[1;31m• \033[1;33mINSTALLING A SCRIPT SET AS TOOLS\033[0m" 
 echo -e "\033[1;33m  FOR NETWORK, SYSTEM AND USER MANAGEMENT\033[0m"
 echo ""
 echo -e "\033[1;32m• \033[1;32mTIP! \033[1;33mUSE THE DARK THEME IN YOUR TERMINAL TO\033[0m"
 echo -e "\033[1;33m  A BETTER EXPERIENCE AND VISUALIZATION!\033[0m"
+echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
 echo ""
-echo -e "\033[1;31m[\033[1;33m • \033[1;32mTRANSLATED BY JALINGKUT TRIX\033[1;33m  •\033[1;31m]\033[0m"
-echo ""
-echo "-----------------------------------------------------------------------"
-read -p "$(echo -e "\033[1;36mDO YOU WISH TO CONTINUE \033[1;31m? \033[1;33m[S/N]:\033[1;37m ")" -e -i s resp
-[[ $resp = @(n|N) ]] && rm $HOME/Plus && exit 0
-cp /etc/ssh/sshd_config /etc/ssh/sshd_back
-wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/rockneters/cmorgan/main/Install/sshd_config > /dev/null 2>&1
+#-----------------------------------------------------------------------------------------------------------------
+echo -ne "\033[1;36mGENERATE AS FREE KEY [N/Y]: \033[1;37m"; read x
+[[ $x = @(n|N) ]] && exit
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
 service ssh restart  > /dev/null 2>&1
+echo -e "\n\033[1;36mCHECKING... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/rockneters/cmorgan/main/Install/list > /dev/null 2>&1; verif_key
+sleep 3s
 echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
+rm version* > /dev/null 2>&1
+wget https://raw.githubusercontent.com/rockneters/cmorgan/main/version > /dev/null 2>&1
+#-----------------------------------------------------------------------------------------------------------------
+echo -e "\n\033[1;32mKEY VALID!\033[1;32m"
+sleep 1s
 echo ""
 [[ -f "$HOME/users.db" ]] && {
     clear
     echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
     echo ""
-	echo -e "\033[1;33m• \033[1;31mATTENTION \033[1;33m• \033[0m"
+	echo -e "                 \033[1;33m• \033[1;31mATTENTION \033[1;33m• \033[0m"
 	echo ""
     echo -e "\033[1;33mA Users Database\033[1;32m(users.db) \033[1;33mWas" 
     echo -e "Found! Do you want to keep it preserving the limit"
@@ -110,7 +101,7 @@ fun_attlist () {
 fun_bar 'fun_attlist'
 clear
 echo ""
-echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALLING PACKAGES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALLING PACKAGES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
 echo ""
 echo -e "\033[1;33mSOME PACKAGES ARE EXTREMELY BIG !\033[0m"
 echo ""
@@ -120,28 +111,21 @@ for _prog in ${_pacotes[@]}; do
     apt install $_prog -y
 done
 pip install speedtest-cli
-apt install ufw
 }
 fun_bar 'inst_pct'
-[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp ; ufw allow 777/tcp ; ufw allow 222/tcp
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
 clear
 echo ""
-echo -e "\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINISHING \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINISHING \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
 echo ""
-echo -e "\033[1;33mCOMPLETING FUNCTIONS AND DEFINITIONS! \033[0m"
+echo -e "      \033[1;33mCOMPLETING FUNCTIONS AND DEFINITIONS! \033[0m"
 echo ""
 fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
 clear
 echo ""
 cd $HOME
-echo -e "\033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
+echo -e "        \033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
 echo ""
 echo -e "\033[1;31m \033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"
-echo -e "\033[1;33m MORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@RocknetStore\033[0m"
+echo -e "\033[1;33m MORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@SSHPLUS\033[0m"
 rm -rf $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
-else
-echo -e "${red}Permintaan Ditolak!${NC}";
-echo "Hanya untuk pengguna terdaftar"
-rm -rf $HOME/Plus > /dev/null 2>&1
-cd
-fi
